### ISSUE TITLE
Tool choice - Collaboration

### ISSUE THREAD

**Issue by VertyLynn** [brainhack-school2020/3D_fMRI_visualization#2]
Hi @FrancoisPgm!

Your project is very interesting!! You named three tools (Nilearn, Visbrain, Brainbrowser), from what you know what are the strengths and weaknesses of each? What will guide your tool choice?

Also, my project will be about learning to predict cognitive performance with fmri data via Nilearn. Saw that you didn't mention the data set you'll use yet. Would like to know if we could use the same dataset and learn from each other. 

Best,
Lynn

**Comment by FrancoisPgm** [comment]
Hi @VertyLynn,
For the different tools I have to admit I am only familiar with nilearn, for which the advantage would be its simplicity to integrate in notebooks and ist speed, the weakness would be it is not high resolution.
For visbrain, I just learnt its existence with Karim's talk. It seems to be focused on MEG data so that would be a weakness in my case.
For Brainbrowser, I tried their online demo, and the strength would be it seems to be in higher resolution than nilearn but it is quite slow to render and it seems to require a dedicated web page, I don't know if it would fit in a notebook.

**Comment by FrancoisPgm** [comment]
Regarding the dataset, I don't have any restriction since any 4D fMRI data should be accepted as input of the visualizer. So I would be glad to use the same dataset as you.
